---
kind: pipeline
type: kubernetes
name: default

node_selector:
  drone: "true"

steps:
  - name: build
    pull: always
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      repo: kradalby/map
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master

  - name: deploy
    pull: always
    image: kradalby/drone-kubectl
    environment:
      KUBERNETES_CERT:
        from_secret: kubernetes_cert
      KUBERNETES_SERVER:
        from_secret: kubernetes_server
      KUBERNETES_TOKEN:
        from_secret: kubernetes_token
    commands:
      - kubectl -n map set image deployment/map common=kradalby/map:${DRONE_COMMIT_SHA:0:8} --record
      - kubectl -n map rollout status deployment map
    when:
      branch:
        - master
      event:
        - push

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token

---
kind: secret
name: discord_webhook_id
get:
  path: discord-build
  name: id

---
kind: secret
name: discord_webhook_token
get:
  path: discord-build
  name: token

---
kind: secret
name: docker_username
get:
  path: docker
  name: username

---
kind: secret
name: docker_password
get:
  path: docker
  name: password
