pipeline:
  build:
    image: plugins/docker
    repo: kradalby/map.kradalby.no
    auto_tag: true
    secrets: [ docker_username, docker_password ]

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    deployment: map-kradalby-no-deployment
    repo: kradalby/map.kradalby.no
    container: [map]
    namespace: default
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    tag:                 
        - "${DRONE_TAG}"
    when:
        event: tag
        
  notify:
    image: drillster/drone-email
    host: mail.ntnu.fap.no
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
